rule_files:
- '/etc/prometheus/*-rules.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9100"]

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]
