#########################################################################
# Title:            Community: Syncthing                                #
# Author(s):        asdf                                                #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  syncthing/syncthing                                 #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: syncthing
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: syncthing
    state: absent

- name: Create htpasswd
  htpasswd:
    path: "/opt/nginx-proxy/htpasswd/{{ item }}.{{ user.domain }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  with_items:
    - syncthing

- name: Create syncthing directory
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
      - /opt/syncthing/config
      - /mnt/local/Sync

- name: Create and start container
  docker_container:
    name: syncthing
    image: "syncthing/syncthing"
    pull: yes
    published_ports:
      - "127.0.0.1:8384:8384"
      - 22000:22000/tcp
      - 22000:22000/udp
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "syncthing.{{ user.domain }}"
      VIRTUAL_PORT: "8384"
      LETSENCRYPT_HOST: "syncthing.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      STGUIADDRESS: "0.0.0.0:8384"
    volumes:
      - "/mnt:/var/syncthing/mnt"
      - "/opt/syncthing/config:/var/syncthing/config"
      - "/mnt/local/Sync:/var/syncthing/Sync"
    networks:
      - name: cloudbox
        aliases:
          - syncthing
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
