#########################################################################
# Title:            Community: Minecraft Backup                         #
# Author(s):        svenz                                               #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  itzg/mc-backup                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: minecraft-backup
    state: absent

- name: Create backup directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/minecraft/backups

- name: Create and start container
  docker_container:
    name: minecraft-backup
    image: itzg/mc-backup
    pull: yes
    env:
      TZ: "{{ tz }}"
      UID: "{{ uid }}"
      GID: "{{ gid }}"
      PRUNE_BACKUPS_DAYS: 10
      RCON_HOST: minecraft
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/minecraft/data:/data:ro"
      - "/opt/minecraft/backups:/backups"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - minecraft-backup
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
